name:                santorini-cli
version:             0.1.0.0
github:              "steve-nekoliczak/santorini-cli"
license:             BSD3
author:              "Steve Nekoliczak"
maintainer:          "steve.nekoliczak@protonmail.com"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/steve-nekoliczak/santorini-cli#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- transformers
- brick
- vty
- mtl
- text
- split
- microlens
- microlens-mtl
- microlens-th

ghc-options:
- -Wall
- -Wno-unused-top-binds

default-extensions: NamedFieldPuns OverloadedRecordDot

library:
  source-dirs: src

executables:
  santorini-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santorini-cli

tests:
  santorini-cli-test:
    main:                Spec.hs
    source-dirs:
      - test
      - test/factory
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santorini-cli
